classifier:
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: 1.0
  device: null
  early_stopping_rounds: null
  enable_categorical: false
  eval_metric: null
  feature_types: null
  gamma: null
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: 0.01
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: null
  max_leaves: null
  min_child_weight: 13
  missing: .nan
  monotone_constraints: null
  multi_strategy: null
  n_estimators: 621
  n_jobs: null
  num_parallel_tree: null
  objective: multi:softprob
  random_state: null
  reg_alpha: 0
  reg_lambda: 0
  sampling_method: null
  scale_pos_weight: null
  subsample: 1.0
  tree_method: null
  validate_parameters: null
  verbosity: null
scaler:
  copy: true
  with_mean: true
  with_std: true
selectkbest:
  k: 42
  score_func: !!python/name:sklearn.feature_selection._univariate_selection.f_classif ''
